# Generated by Django 2.0.5 on 2018-06-05 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_myuser_tag'),
        ('forum', '0007_comment_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
                ('time', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_from_user', to='authentication.MyUser')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_to_user', to='authentication.MyUser')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_from_user', to='authentication.MyUser'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_to_user', to='authentication.MyUser'),
        ),
    ]
