# Generated by Django 2.0.5 on 2018-06-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_myuser_tag'),
        ('forum', '0008_auto_20180605_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislike_user',
            field=models.ManyToManyField(related_name='comment_dislike_user', to='authentication.MyUser'),
        ),
        migrations.AddField(
            model_name='comment',
            name='like_user',
            field=models.ManyToManyField(related_name='comment_like_user', to='authentication.MyUser'),
        ),
    ]
