# Generated by Django 2.0.5 on 2018-05-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20180524_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='history',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
