# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat_message.proto',
  package='chat',
  syntax='proto3',
  serialized_pb=_b('\n\x12\x63hat_message.proto\x12\x04\x63hat\"\xa2\x01\n\x0f\x43hatMessageItem\x12\x10\n\x08\x63lientId\x18\x01 \x01(\x05\x12\x12\n\nclientName\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x10\n\x08imageUrl\x18\x04 \x01(\t\x12\x11\n\ttimeStamp\x18\x05 \x01(\x05\x12\x0f\n\x07\x66ileUrl\x18\x06 \x01(\t\x12\x10\n\x08\x66ileSize\x18\x07 \x01(\x05\x12\x10\n\x08\x66ileName\x18\x08 \x01(\t\"\xd2\x01\n\x0b\x43hatMessage\x12$\n\x04type\x18\x01 \x01(\x0e\x32\x16.chat.ChatMessage.Type\x12\x30\n\x11\x63hat_message_item\x18\x02 \x03(\x0b\x32\x15.chat.ChatMessageItem\x12-\n\x0e\x63urrent_client\x18\x03 \x03(\x0b\x32\x15.chat.ChatMessageItem\"<\n\x04Type\x12\x10\n\x0c\x43HAT_MESSAGE\x10\x00\x12\x10\n\x0c\x43LIENT_ENTER\x10\x01\x12\x10\n\x0c\x43LIENT_LEAVE\x10\x02\x62\x06proto3')
)



_CHATMESSAGE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='chat.ChatMessage.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CHAT_MESSAGE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLIENT_ENTER', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLIENT_LEAVE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=344,
  serialized_end=404,
)
_sym_db.RegisterEnumDescriptor(_CHATMESSAGE_TYPE)


_CHATMESSAGEITEM = _descriptor.Descriptor(
  name='ChatMessageItem',
  full_name='chat.ChatMessageItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientId', full_name='chat.ChatMessageItem.clientId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clientName', full_name='chat.ChatMessageItem.clientName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='chat.ChatMessageItem.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imageUrl', full_name='chat.ChatMessageItem.imageUrl', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='chat.ChatMessageItem.timeStamp', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fileUrl', full_name='chat.ChatMessageItem.fileUrl', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fileSize', full_name='chat.ChatMessageItem.fileSize', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fileName', full_name='chat.ChatMessageItem.fileName', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=191,
)


_CHATMESSAGE = _descriptor.Descriptor(
  name='ChatMessage',
  full_name='chat.ChatMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='chat.ChatMessage.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chat_message_item', full_name='chat.ChatMessage.chat_message_item', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_client', full_name='chat.ChatMessage.current_client', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CHATMESSAGE_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=404,
)

_CHATMESSAGE.fields_by_name['type'].enum_type = _CHATMESSAGE_TYPE
_CHATMESSAGE.fields_by_name['chat_message_item'].message_type = _CHATMESSAGEITEM
_CHATMESSAGE.fields_by_name['current_client'].message_type = _CHATMESSAGEITEM
_CHATMESSAGE_TYPE.containing_type = _CHATMESSAGE
DESCRIPTOR.message_types_by_name['ChatMessageItem'] = _CHATMESSAGEITEM
DESCRIPTOR.message_types_by_name['ChatMessage'] = _CHATMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChatMessageItem = _reflection.GeneratedProtocolMessageType('ChatMessageItem', (_message.Message,), dict(
  DESCRIPTOR = _CHATMESSAGEITEM,
  __module__ = 'chat_message_pb2'
  # @@protoc_insertion_point(class_scope:chat.ChatMessageItem)
  ))
_sym_db.RegisterMessage(ChatMessageItem)

ChatMessage = _reflection.GeneratedProtocolMessageType('ChatMessage', (_message.Message,), dict(
  DESCRIPTOR = _CHATMESSAGE,
  __module__ = 'chat_message_pb2'
  # @@protoc_insertion_point(class_scope:chat.ChatMessage)
  ))
_sym_db.RegisterMessage(ChatMessage)


# @@protoc_insertion_point(module_scope)
