# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notification_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='notification_message.proto',
  package='chat',
  syntax='proto3',
  serialized_pb=_b('\n\x1anotification_message.proto\x12\x04\x63hat\"\xe1\x03\n\x10NotificationItem\x12)\n\x04type\x18\x01 \x01(\x0e\x32\x1b.chat.NotificationItem.Type\x12\x14\n\x0c\x66romClientId\x18\x02 \x01(\x05\x12\x12\n\ntoClientId\x18\x03 \x01(\x05\x12\x16\n\x0e\x66romClientName\x18\x04 \x01(\t\x12\x14\n\x0ctoClientName\x18\x05 \x01(\t\x12\x10\n\x08imageUrl\x18\x06 \x01(\t\x12\x0b\n\x03tag\x18\x07 \x03(\t\x12\x0c\n\x04text\x18\x08 \x01(\t\x12\x11\n\tcommentId\x18\t \x01(\x05\x12\x13\n\x0bisAnonymous\x18\n \x01(\x08\x12\x10\n\x08isPublic\x18\x0b \x01(\x08\"\xe2\x01\n\x04Type\x12\x16\n\x12REQUEST_ADD_FRIEND\x10\x00\x12\x14\n\x10\x41GREE_ADD_FRIEND\x10\x01\x12\x17\n\x13\x44ISAGREE_ADD_FRIEND\x10\x02\x12\x19\n\x15REQUEST_DELETE_FRIEND\x10\x03\x12\x0b\n\x07\x41\x44\x44_TAG\x10\x04\x12\x0f\n\x0b\x41\x44\x44_COMMENT\x10\x05\x12\x10\n\x0cLIKE_COMMENT\x10\x06\x12\x17\n\x13\x43\x41NCEL_LIKE_COMMENT\x10\x07\x12\x13\n\x0f\x44ISLIKE_COMMENT\x10\x08\x12\x1a\n\x16\x43\x41NCEL_DISLIKE_COMMENT\x10\t\"A\n\x0cNotification\x12\x31\n\x11notification_item\x18\x01 \x03(\x0b\x32\x16.chat.NotificationItemb\x06proto3')
)



_NOTIFICATIONITEM_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='chat.NotificationItem.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REQUEST_ADD_FRIEND', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AGREE_ADD_FRIEND', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISAGREE_ADD_FRIEND', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REQUEST_DELETE_FRIEND', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADD_TAG', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADD_COMMENT', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LIKE_COMMENT', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CANCEL_LIKE_COMMENT', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISLIKE_COMMENT', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CANCEL_DISLIKE_COMMENT', index=9, number=9,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=292,
  serialized_end=518,
)
_sym_db.RegisterEnumDescriptor(_NOTIFICATIONITEM_TYPE)


_NOTIFICATIONITEM = _descriptor.Descriptor(
  name='NotificationItem',
  full_name='chat.NotificationItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='chat.NotificationItem.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fromClientId', full_name='chat.NotificationItem.fromClientId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='toClientId', full_name='chat.NotificationItem.toClientId', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fromClientName', full_name='chat.NotificationItem.fromClientName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='toClientName', full_name='chat.NotificationItem.toClientName', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imageUrl', full_name='chat.NotificationItem.imageUrl', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tag', full_name='chat.NotificationItem.tag', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='chat.NotificationItem.text', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='commentId', full_name='chat.NotificationItem.commentId', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isAnonymous', full_name='chat.NotificationItem.isAnonymous', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isPublic', full_name='chat.NotificationItem.isPublic', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _NOTIFICATIONITEM_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=518,
)


_NOTIFICATION = _descriptor.Descriptor(
  name='Notification',
  full_name='chat.Notification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='notification_item', full_name='chat.Notification.notification_item', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=520,
  serialized_end=585,
)

_NOTIFICATIONITEM.fields_by_name['type'].enum_type = _NOTIFICATIONITEM_TYPE
_NOTIFICATIONITEM_TYPE.containing_type = _NOTIFICATIONITEM
_NOTIFICATION.fields_by_name['notification_item'].message_type = _NOTIFICATIONITEM
DESCRIPTOR.message_types_by_name['NotificationItem'] = _NOTIFICATIONITEM
DESCRIPTOR.message_types_by_name['Notification'] = _NOTIFICATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NotificationItem = _reflection.GeneratedProtocolMessageType('NotificationItem', (_message.Message,), dict(
  DESCRIPTOR = _NOTIFICATIONITEM,
  __module__ = 'notification_message_pb2'
  # @@protoc_insertion_point(class_scope:chat.NotificationItem)
  ))
_sym_db.RegisterMessage(NotificationItem)

Notification = _reflection.GeneratedProtocolMessageType('Notification', (_message.Message,), dict(
  DESCRIPTOR = _NOTIFICATION,
  __module__ = 'notification_message_pb2'
  # @@protoc_insertion_point(class_scope:chat.Notification)
  ))
_sym_db.RegisterMessage(Notification)


# @@protoc_insertion_point(module_scope)
