# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-13 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20161130_1348'),
        ('authentication', '0002_auto_20161129_0834'),
    ]

    operations = [
    ]
