# Generated by Django 2.0.5 on 2018-05-14 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_merge_20180513_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='invitable',
        ),
    ]
