# Generated by Django 2.0.5 on 2018-05-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_myuser_invitable'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='friend',
            field=models.ManyToManyField(related_name='_myuser_friend_+', to='authentication.MyUser'),
        ),
    ]
