# Generated by Django 2.0.5 on 2018-05-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20180515_2024'),
        ('authentication', '0005_myuser_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='chat_room',
            field=models.ManyToManyField(to='chat.ChatRoomGroup'),
        ),
    ]
