# Generated by Django 2.0.5 on 2018-06-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_myuser_chat_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='tag',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
