# Generated by Django 2.0.5 on 2018-06-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_myuser_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='tag',
            field=models.CharField(default='[]', max_length=300),
        ),
    ]
