# Generated by Django 2.0.5 on 2018-06-05 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20180604_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='tag',
        ),
    ]
